### ISSUE TITLE
Communicate between devtools and web page

### ISSUE THREAD

**Issue by hosseind88** [llagerlof/fresh-chrome-extension#1]
Hi, I want to use js Custom Events for our web app that is going to be a micro-frontend and I want to make an extention that appears in devtools panel and it's a react application that runs a listener and whenever we do a `document.dispatchEvent(...)` it shows the event content. but I don't know how to make this communication between web app and the devtools panel app.
can you please help me?

**Comment by llagerlof** [comment]
> I want to make an extention that appears in devtools panel

Sorry, I don't know how to do that.
